image: maven:3.6.3-jdk-8

stages:
  - start
  - build
  - deploy
  - clean


variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

before_script:
  - echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                            https://maven.apache.org/xsd/settings-1.0.0.xsd">
                <proxies>
                    <!--proxy>
                        <active>true</active>
                        <host>10.0.1.8</host>
                        <port>8000</port>
                    </proxy>-->                
                </proxies>
                <servers>
                    <server>
                        <id>StagingServer8888</id>
                        <username>tomcat</username>
                        <password>s3cret</password>
                    </server>
                    <server>
                        <id>ProductionServer8889</id>
                        <username>tomcat</username>
                        <password>s3cret</password>
                    </server>                
                </servers>
          </settings>' > $HOME/.m2/settings.xml
clean:
  stage: start
  script:
    - mvn $MAVEN_CLI_OPTS -U clean

purge_dependencies:
  stage: start
  script:
    - mvn $MAVEN_CLI_OPTS dependency:purge-local-repository

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS install package
    
  artifacts:
    paths:
    - target/*.war
    expire_in: 1 week